// Core — generated by @web-kits/audio (do not edit)
// patch: Core
//
// Source: raphaelsalaja/audio @ main · .web-kits/core.json
// Fetched: 2026-04-26
// License: MIT (Raphael Salaja, 2026)
//
// TIER-1 ONLY. We physically removed every sound that's not in the bytesize
// audio playbook (`docs/audio-playbook.md`) — Hover, Tap, Key-Press,
// Checkbox, Tick, Scroll-Snap, Focus, Blur, Toggle-On, Toggle-Off, Select,
// Deselect, Boop, Bounce, Spring, Expand, Collapse, Complete, Level-Up,
// Confetti, Save, Ding, Notification, Mention, Badge, Info, Sparkle, Star,
// Delete, Warning, Whoosh, Page-Enter, Page-Exit, Tab-Switch, Drawer-Open,
// Drawer-Close, Modal-Open, Modal-Close, Dropdown-Close, Slide-Up,
// Slide-Down, Send, Receive, Command, Escape, Undo, Archive, Sync, Heart,
// Streak, Loading-Start, Loading-End. The retained 10 cover every Tier-1
// wire site.
//
// Per-sound `gain` values trim a few of the upstream Core defaults so they
// land at the same perceived loudness as the rest of the vocabulary under
// `UNIFORM_GAIN = 1.0` (lib/audio.ts). Click / Pop / Error / Radio / Copy
// were upstream-louder than the original Minimal patch — they have been
// pulled back here. Slide / Swoosh / Dropdown-Open / Progress-Tick / Success
// kept their upstream values.
//
// Bundle weight = 10 SoundDefinition objects. The runtime never decodes
// audio files; sounds are synthesised live via Web Audio.

import type { SoundDefinition, SoundPatch } from "@web-kits/audio";

export const progressTick: SoundDefinition = {
  source: {
    type: "sine",
    frequency: 1400,
    fm: { ratio: 0.5, depth: 50 },
  },
  envelope: { attack: 0, decay: 0.01, sustain: 0, release: 0.004 },
  gain: 0.1,
};

export const click: SoundDefinition = {
  source: {
    type: "sine",
    frequency: { start: 200, end: 700 },
    fm: { ratio: 0.5, depth: 80 },
  },
  envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
  // Trimmed from upstream 0.25 → 0.1 to match the Tier-1 baseline. Click
  // fires on every Quiz option-press; it sits in the background.
  gain: 0.1,
};

export const copy: SoundDefinition = {
  layers: [
    {
      source: { type: "sine", frequency: 1200 },
      envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.006 },
      // Trimmed from upstream 0.16 → 0.08.
      gain: 0.08,
    },
    {
      source: { type: "sine", frequency: 1400 },
      envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.006 },
      delay: 0.04,
      // Trimmed from upstream 0.14 → 0.07.
      gain: 0.07,
    },
  ],
};

export const radio: SoundDefinition = {
  source: {
    type: "sine",
    frequency: { start: 300, end: 900 },
    fm: { ratio: 0.5, depth: 50 },
  },
  envelope: { attack: 0, decay: 0.04, sustain: 0, release: 0.012 },
  // Trimmed from upstream 0.2 → 0.1. Radio fires on every binary toggle and
  // every segmented-control row press — it must not draw attention.
  gain: 0.1,
};

export const pop: SoundDefinition = {
  source: { type: "sine", frequency: { start: 400, end: 150 } },
  envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
  // Trimmed from upstream 0.25 → 0.1. Pop repeats through CallStackECs
  // multi-step traces; the decay rule already attenuates streaks but the
  // first beat needs to land at the same level as Click.
  gain: 0.1,
};

export const slide: SoundDefinition = {
  source: { type: "noise", color: "white" },
  filter: {
    type: "bandpass",
    frequency: 500,
    resonance: 1,
    envelope: { attack: 0.02, peak: 3000, decay: 0.12 },
  },
  envelope: { attack: 0.01, decay: 0.15, sustain: 0, release: 0.05 },
  gain: 0.07,
};

export const dropdownOpen: SoundDefinition = {
  source: { type: "sine", frequency: { start: 500, end: 1200 } },
  envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
  // NavigationSounds beat — softer than its upstream chime so it reads as a
  // settling tap, not an interruption.
  gain: 0.07,
};

export const success: SoundDefinition = {
  layers: [
    {
      source: { type: "sine", frequency: 523 },
      envelope: { attack: 0.003, decay: 0.3, sustain: 0.06, release: 0.1 },
      gain: 0.16,
    },
    {
      source: { type: "sine", frequency: 659 },
      envelope: { attack: 0.003, decay: 0.28, sustain: 0.05, release: 0.1 },
      delay: 0.07,
      gain: 0.14,
    },
    {
      source: { type: "sine", frequency: { start: 784, end: 880 } },
      envelope: { attack: 0.003, decay: 0.32, sustain: 0.06, release: 0.12 },
      delay: 0.14,
      gain: 0.15,
    },
  ],
};

export const error: SoundDefinition = {
  layers: [
    {
      source: {
        type: "sawtooth",
        frequency: { start: 320, end: 140 },
      },
      filter: { type: "lowpass", frequency: 1200 },
      envelope: { attack: 0, decay: 0.25, sustain: 0, release: 0.08 },
      // Trimmed from upstream 0.22 → 0.12. Error is heavy by nature; we
      // don't need additional weight on top.
      gain: 0.12,
    },
    {
      source: {
        type: "square",
        frequency: { start: 180, end: 80 },
      },
      filter: { type: "lowpass", frequency: 800 },
      envelope: { attack: 0, decay: 0.2, sustain: 0, release: 0.06 },
      delay: 0.03,
      // Trimmed from upstream 0.12 → 0.08.
      gain: 0.08,
    },
  ],
};

export const swoosh: SoundDefinition = {
  source: { type: "noise", color: "white" },
  filter: {
    type: "bandpass",
    frequency: 300,
    resonance: 1.8,
    envelope: { attack: 0.01, peak: 4000, decay: 0.08 },
  },
  envelope: { attack: 0.01, decay: 0.12, sustain: 0, release: 0.04 },
  gain: 0.12,
};

export const _patch: SoundPatch = {
  name: "Core",
  author: "Raphael Salaja",
  version: "3.1.0",
  description:
    "Tier-1 bytesize subset of the upstream Core patch — 10 sounds covering every wire site.",
  sounds: {
    "progress-tick": progressTick,
    click,
    copy,
    radio,
    pop,
    slide,
    "dropdown-open": dropdownOpen,
    success,
    error,
    swoosh,
  },
};
