// Minimal — generated by @web-kits/audio (do not edit)
// patch: Minimal
//
// Source: raphaelsalaja/audio @ main · .web-kits/minimal.json
// License: MIT (Raphael Salaja, 2026)
//
// TIER-1 ONLY. We physically removed every sound that's not in the lainlog
// audio playbook (`docs/audio-playbook.md`) — Hover, Tap, Key-Press,
// Toggle-Off, Notification, Info, Warning, Send, Delete, Undo, Tab-Switch,
// Checkbox, Select, Deselect, Collapse, Expand, Page-Enter, Page-Exit.
// Bundle weight = 8 SoundDefinition objects (~0.5 kB gz). The runtime
// never decodes audio files; sounds are synthesised live via Web Audio.

import type { SoundDefinition, SoundPatch } from "@web-kits/audio";

export const click: SoundDefinition = {
  source: { type: "sine", frequency: 800 },
  envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.005 },
  gain: 0.1,
};

export const toggleOn: SoundDefinition = {
  layers: [
    {
      source: { type: "sine", frequency: 880 },
      envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.006 },
      gain: 0.08,
    },
    {
      source: { type: "sine", frequency: 1320 },
      envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.006 },
      delay: 0.03,
      gain: 0.07,
    },
  ],
};

export const success: SoundDefinition = {
  layers: [
    {
      source: { type: "sine", frequency: 523 },
      envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
      gain: 0.1,
    },
    {
      source: { type: "sine", frequency: 784 },
      envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
      delay: 0.06,
      gain: 0.08,
    },
  ],
};

export const error: SoundDefinition = {
  layers: [
    {
      source: { type: "sine", frequency: 300 },
      envelope: { attack: 0, decay: 0.04, sustain: 0, release: 0.012 },
      gain: 0.12,
    },
    {
      source: { type: "sine", frequency: 280 },
      envelope: { attack: 0, decay: 0.04, sustain: 0, release: 0.012 },
      delay: 0.01,
      gain: 0.1,
    },
  ],
};

export const copy: SoundDefinition = {
  layers: [
    {
      source: { type: "sine", frequency: 1000 },
      envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
      gain: 0.08,
    },
    {
      source: { type: "sine", frequency: 1200 },
      envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
      delay: 0.035,
      gain: 0.07,
    },
  ],
};

export const pop: SoundDefinition = {
  source: { type: "sine", frequency: { start: 400, end: 200 } },
  envelope: { attack: 0, decay: 0.04, sustain: 0, release: 0.012 },
  gain: 0.1,
};

export const swoosh: SoundDefinition = {
  source: { type: "sine", frequency: { start: 600, end: 1400 } },
  envelope: { attack: 0.005, decay: 0.04, sustain: 0, release: 0.015 },
  gain: 0.05,
};

export const slide: SoundDefinition = {
  source: { type: "sine", frequency: { start: 800, end: 1100 } },
  envelope: { attack: 0.003, decay: 0.035, sustain: 0, release: 0.012 },
  gain: 0.05,
};

export const _patch: SoundPatch = {
  name: "Minimal",
  author: "Raphael Salaja",
  version: "1.0.0",
  description:
    "Tier-1 lainlog subset of the upstream Minimal patch — sine-based palette for quiet UI feedback.",
  sounds: {
    click,
    "toggle-on": toggleOn,
    success,
    error,
    copy,
    pop,
    swoosh,
    slide,
  },
};
